# - Find libcdim

FIND_PATH(CDIM_INCLUDE_DIR libcdim.h)

FIND_LIBRARY(CDIM_LIBRARIES NAMES cdim)

IF (CDIM_LIBRARIES AND CDIM_INCLUDE_DIR)
	SET(CDIM_FOUND "YES")
ELSE (CDIM_LIBRARIES AND CDIM_INCLUDE_DIR)
	SET(CDOM_FOUND "NO")
ENDIF (CDIM_LIBRARIES AND CDIM_INCLUDE_DIR)

IF (CDIM_FOUND)
	IF (NOT CDIM_FIND_QUIETLY)
		MESSAGE(STATUS "Found cdim library: ${CDIM_LIBRARIES}")
	ENDIF (NOT CDIM_FIND_QUIETLY)
ELSE (CDIM_FOUND)
	IF (CDIM_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find CDIM library")
	ENDIF (CDIM_FIND_REQUIRED)
ENDIF (CDIM_FOUND)

MARK_AS_ADVANCED(CDIM_LIBRARIES CDIM_INCLUDE_DIR)
